import { Router } from "express";
import { z } from "zod";
import { requireAnyPermission, requireAuthentication } from "../../middlewares/auth.middleware";
import { createCustomFieldGroupSchema, createCustomFieldSchema, listCustomFieldGroupSchema, listCustomFieldSchema, reorderCustomFieldSchema, statusCustomFieldGroupSchema, statusCustomFieldSchema, updateCustomFieldGroupSchema, updateCustomFieldSchema } from "./custom-fields.schema";
import { createCustomField, getCustomField, listCustomFields, reorderCustomFields, setCustomFieldStatus, updateCustomField } from "./custom-fields.service";
import { createCustomFieldGroup, listCustomFieldGroups, setCustomFieldGroupStatus, updateCustomFieldGroup } from "./custom-field-groups.service";
import { customFieldEntityTypes } from "./custom-fields.types";
import { getInstitutionProgramScope } from "../institutions/institution-program-scope";
import { getRuntimeCustomFieldDefinitions, getRuntimeCustomFields, saveRuntimeCustomFields, type RuntimeCustomFieldEntityType } from "../leads/sale-custom-fields.service";
export const customFieldsRouter = Router(); customFieldsRouter.use(requireAuthentication);
const id = z.uuid(); const message: Record<string, string> = { scope_denied: "Bạn không có quyền truy cập chương trình tuyển sinh này.", not_found: "Không tìm thấy trường dữ liệu.", duplicate_key: "Mã trường đã tồn tại trong phạm vi áp dụng.", program_not_found: "Không tìm thấy chương trình tuyển sinh.", group_not_found: "Không tìm thấy nhóm trường dữ liệu đang hoạt động.", duplicate_group_key: "Mã nhóm trường đã tồn tại.", system_group_locked: "Nhóm hệ thống không thể chỉnh sửa cấu hình.", group_archived: "Nhóm trường dữ liệu đã được lưu trữ.", group_not_empty: "Hãy chuyển hoặc lưu trữ các trường trong nhóm trước khi lưu trữ nhóm.", data_type_locked: "Không thể đổi kiểu dữ liệu khi trường đã có giá trị.", scope_locked: "Không thể đổi phạm vi của trường đã tạo.", already_archived: "Trường dữ liệu đã được lưu trữ.", different_group: "Chỉ có thể sắp xếp lại các trường cùng nhóm." };
function fail(response: any, result: any) { response.status(result.reason === "scope_denied" ? 403 : ["duplicate_key", "duplicate_group_key"].includes(result.reason) ? 409 : ["not_found", "group_not_found"].includes(result.reason) ? 404 : 400).json({ message: message[result.reason] ?? "Không thể xử lý trường dữ liệu." }); }
const runtimeEntityTypes = ["MARKETING_CAMPAIGN", "MARKETING_FORM", "ADMISSION_PROFILE", "ADMISSION_DOCUMENT", "ADMISSION_STATUS", "ADMISSION_MAJOR"] as const;
const runtimeEntitySchema = z.enum(runtimeEntityTypes);
const runtimeQuerySchema = z.object({ entityId: z.uuid().optional() });
const runtimeValuesSchema = z.object({ values: z.record(z.uuid(), z.unknown().nullable()).default({}) });
const runtimePermissions: Record<typeof runtimeEntityTypes[number], { view: string[]; edit: string[] }> = {
  MARKETING_CAMPAIGN: { view: ["campaign.view_all", "campaign.view", "campaign.view_own", "campaign.create", "campaign.update", "campaign.update_own"], edit: ["campaign.create", "campaign.update", "campaign.update_own"] },
  MARKETING_FORM: { view: ["campaign.view_all", "marketing_form.manage", "marketing_form.create", "marketing_form.update_own"], edit: ["marketing_form.manage", "marketing_form.create", "marketing_form.update_own"] },
  ADMISSION_PROFILE: { view: ["admission.view_all", "admission.view", "admission.update"], edit: ["admission.update"] },
  ADMISSION_DOCUMENT: { view: ["admission.view_all", "admission.view", "admission_document.view", "admission_document.upload", "admission.approve"], edit: ["admission_document.upload", "admission.approve"] },
  ADMISSION_STATUS: { view: ["admission.view_all", "admission.view", "admission_status.update"], edit: ["admission_status.update"] },
  ADMISSION_MAJOR: { view: ["admission_major.manage"], edit: ["admission_major.manage"] },
};
function hasRuntimePermission(req: any, entityType: typeof runtimeEntityTypes[number], mode: "view" | "edit") { return runtimePermissions[entityType][mode].some((permission) => req.authUser!.permissions.includes(permission)); }
customFieldsRouter.get("/runtime/:entityType", async (req, res, next) => { try { const type = runtimeEntitySchema.safeParse(req.params.entityType), query = runtimeQuerySchema.safeParse(req.query); if (!type.success || !query.success) return res.status(400).json({ message: "Loại đối tượng hoặc mã bản ghi không hợp lệ." }); if (!hasRuntimePermission(req, type.data, "view")) return res.status(403).json({ message: "Bạn không có quyền xem trường dữ liệu của form này." }); const canEdit = hasRuntimePermission(req, type.data, "edit"); const scope = getInstitutionProgramScope(req); const data = query.data.entityId ? await getRuntimeCustomFields(req.authUser!, type.data as RuntimeCustomFieldEntityType, query.data.entityId, canEdit, scope) : await getRuntimeCustomFieldDefinitions(req.authUser!, type.data as RuntimeCustomFieldEntityType, canEdit, scope); if (!data) return res.status(404).json({ message: "Không tìm thấy bản ghi trong phạm vi truy cập." }); res.json(data); } catch (e) { next(e); } });
customFieldsRouter.patch("/runtime/:entityType/:entityId", async (req, res, next) => { try { const type = runtimeEntitySchema.safeParse(req.params.entityType), entityId = id.safeParse(req.params.entityId), body = runtimeValuesSchema.safeParse(req.body); if (!type.success || !entityId.success || !body.success) return res.status(400).json({ message: "Giá trị trường dữ liệu không hợp lệ." }); if (!hasRuntimePermission(req, type.data, "edit")) return res.status(403).json({ message: "Bạn không có quyền cập nhật trường dữ liệu của form này." }); const values = Object.entries(body.data.values).map(([fieldId, value]) => ({ fieldId, value })); const result = await saveRuntimeCustomFields(req.authUser!, type.data as RuntimeCustomFieldEntityType, entityId.data, values, getInstitutionProgramScope(req), req.ip); if (!result.ok) return res.status(result.reason === "not_found" ? 404 : result.reason === "sensitive_forbidden" ? 403 : 400).json({ message: result.reason === "invalid" ? "Giá trị trường bắt buộc hoặc kiểu dữ liệu không hợp lệ." : "Không thể lưu trường dữ liệu tùy chỉnh." }); res.json({ message: "Đã lưu trường dữ liệu tùy chỉnh." }); } catch (e) { next(e); } });
customFieldsRouter.get("/", requireAnyPermission("custom_field.view"), async (req, res, next) => { try { const parsed = listCustomFieldSchema.safeParse(req.query); if (!parsed.success) return res.status(400).json({ message: "Tham số không hợp lệ." }); const result = await listCustomFields(req.authUser!, parsed.data); if (!result.ok) return fail(res, result); res.json(result.data); } catch (e) { next(e); } });
customFieldsRouter.get("/groups", requireAnyPermission("custom_field.view"), async (req, res, next) => { try { const parsed = listCustomFieldGroupSchema.safeParse(req.query); if (!parsed.success) return res.status(400).json({ message: "Tham số nhóm trường không hợp lệ." }); res.json(await listCustomFieldGroups(parsed.data)); } catch (e) { next(e); } });
customFieldsRouter.post("/groups", requireAnyPermission("custom_field.manage_groups", "custom_field.create"), async (req, res, next) => { try { const parsed = createCustomFieldGroupSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: "Dữ liệu nhóm trường không hợp lệ.", issues: parsed.error.issues }); const result = await createCustomFieldGroup(req.authUser!, parsed.data, req.ip); if (!result.ok) return fail(res, result); res.status(201).json(result.data); } catch (e) { next(e); } });
customFieldsRouter.patch("/groups/:id/status", requireAnyPermission("custom_field.manage_groups", "custom_field.archive"), async (req, res, next) => { try { const groupId = id.safeParse(req.params.id), body = statusCustomFieldGroupSchema.safeParse(req.body); if (!groupId.success || !body.success) return res.status(400).json({ message: "Trạng thái nhóm trường không hợp lệ." }); const result = await setCustomFieldGroupStatus(req.authUser!, groupId.data, body.data.status, req.ip); if (!result.ok) return fail(res, result); res.json(result.data); } catch (e) { next(e); } });
customFieldsRouter.patch("/groups/:id", requireAnyPermission("custom_field.manage_groups", "custom_field.update"), async (req, res, next) => { try { const groupId = id.safeParse(req.params.id), body = updateCustomFieldGroupSchema.safeParse(req.body); if (!groupId.success || !body.success) return res.status(400).json({ message: "Dữ liệu nhóm trường không hợp lệ.", issues: body.success ? undefined : body.error.issues }); const result = await updateCustomFieldGroup(req.authUser!, groupId.data, body.data, req.ip); if (!result.ok) return fail(res, result); res.json(result.data); } catch (e) { next(e); } });
customFieldsRouter.patch("/reorder", requireAnyPermission("custom_field.update"), async (req, res, next) => { try { const parsed = reorderCustomFieldSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: "Dữ liệu sắp xếp không hợp lệ." }); const result = await reorderCustomFields(req.authUser!, parsed.data.fieldIds, req.ip); if (!result.ok) return fail(res, result); res.json({ message: "Đã cập nhật thứ tự trường dữ liệu." }); } catch (e) { next(e); } });
customFieldsRouter.get("/entity/:entityType", requireAnyPermission("custom_field.view"), async (req, res, next) => { try { const type = z.enum(customFieldEntityTypes).safeParse(req.params.entityType); if (!type.success) return res.status(400).json({ message: "Loại đối tượng không hợp lệ." }); const result = await listCustomFields(req.authUser!, { entityType: type.data, includeArchived: false }); if (!result.ok) return fail(res, result); res.json(result.data.filter((field) => field.isActive)); } catch (e) { next(e); } });
customFieldsRouter.post("/", requireAnyPermission("custom_field.create"), async (req, res, next) => { try { const parsed = createCustomFieldSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: "Dữ liệu trường không hợp lệ.", issues: parsed.error.issues }); if (parsed.data.isSensitive && !req.authUser!.permissions.includes("custom_field.edit_sensitive")) return res.status(403).json({ message: "Bạn không có quyền cấu hình trường nhạy cảm." }); if (parsed.data.options?.length && !req.authUser!.permissions.includes("custom_field.manage_options")) return res.status(403).json({ message: "Bạn không có quyền quản lý lựa chọn trường dữ liệu." }); const result = await createCustomField(req.authUser!, parsed.data, req.ip); if (!result.ok) return fail(res, result); res.status(201).json(result.data); } catch (e) { next(e); } });
customFieldsRouter.patch("/:id/status", requireAnyPermission("custom_field.archive"), async (req, res, next) => { try { const fieldId = id.safeParse(req.params.id), body = statusCustomFieldSchema.safeParse(req.body); if (!fieldId.success || !body.success) return res.status(400).json({ message: "Trạng thái trường không hợp lệ." }); const result = await setCustomFieldStatus(req.authUser!, fieldId.data, body.data.status, req.ip); if (!result.ok) return fail(res, result); res.json(result.data); } catch (e) { next(e); } });
customFieldsRouter.get("/:id", requireAnyPermission("custom_field.view"), async (req, res, next) => { try { const parsed = id.safeParse(req.params.id); if (!parsed.success) return res.status(400).json({ message: "Mã trường không hợp lệ." }); const result = await getCustomField(req.authUser!, parsed.data); if (!result.ok) return fail(res, result); res.json(result.data); } catch (e) { next(e); } });
customFieldsRouter.patch("/:id", requireAnyPermission("custom_field.update"), async (req, res, next) => { try { const fieldId = id.safeParse(req.params.id), body = updateCustomFieldSchema.safeParse(req.body); if (!fieldId.success || !body.success) return res.status(400).json({ message: "Dữ liệu cập nhật không hợp lệ.", issues: body.success ? undefined : body.error.issues }); if ((body.data.isSensitive === true || body.data.defaultValue !== undefined) && !req.authUser!.permissions.includes("custom_field.edit_sensitive")) return res.status(403).json({ message: "Bạn không có quyền cấu hình trường nhạy cảm." }); if (body.data.options !== undefined && !req.authUser!.permissions.includes("custom_field.manage_options")) return res.status(403).json({ message: "Bạn không có quyền quản lý lựa chọn trường dữ liệu." }); const result = await updateCustomField(req.authUser!, fieldId.data, body.data, req.ip); if (!result.ok) return fail(res, result); res.json(result.data); } catch (e) { next(e); } });
