import { Prisma } from "../../generated/prisma/client";
import { prisma } from "../../database/prisma";
import type { AuthUser } from "../auth/auth.types";
import { serializeCustomField } from "./custom-fields.serializer";
import type { CustomFieldInput } from "./custom-fields.types";

const groupSelect = { id: true, group_key: true, group_label: true, description: true, is_system: true, is_active: true, display_order: true } as const;
const select = { id: true, field_key: true, field_label: true, description: true, entity_type: true, group_id: true, custom_field_groups: { select: groupSelect }, scope_type: true, program_id: true, field_type: true, is_required: true, is_active: true, archived_at: true, is_searchable: true, is_filterable: true, is_sensitive: true, display_order: true, options: true, validation_rules: true, default_value: true, created_at: true, updated_at: true } as const;
function allScope(actor: AuthUser) { return actor.accessScope === "ALL"; }
function canConfigureCustomFields(actor: AuthUser) { return actor.permissions.some((permission) => permission.startsWith("custom_field.")); }
function canAccess(actor: AuthUser, _programId: string | null) { return allScope(actor) || canConfigureCustomFields(actor); }
function assertScope(actor: AuthUser, programId: string | undefined) { if (!canAccess(actor, programId ?? null)) return { ok: false as const, reason: "scope_denied" as const }; return { ok: true as const }; }
function json(value: unknown) { return value === undefined ? undefined : value as Prisma.InputJsonValue; }
function auditPayload(field: any) { const base = { fieldId: field.id, entityType: field.entity_type, groupId: field.group_id, fieldKey: field.field_key, scopeType: field.scope_type, programId: field.program_id, fieldType: field.field_type, isRequired: field.is_required, isActive: field.is_active, isSearchable: field.is_sensitive ? false : field.is_searchable, isFilterable: field.is_sensitive ? false : field.is_filterable, isSensitive: field.is_sensitive, displayOrder: field.display_order }; return field.is_sensitive ? base : { ...base, fieldLabel: field.field_label, options: field.options, defaultValue: field.default_value }; }
async function activeGroup(groupId: string, entityType: string) { return prisma.custom_field_groups.findFirst({ where: { id: groupId, entity_type: entityType, is_active: true, archived_at: null }, select: { id: true } }); }

export async function listCustomFields(actor: AuthUser, query: { entityType?: string; scopeType?: string; programId?: string; includeArchived: boolean }) {
  if (query.programId && !canAccess(actor, query.programId)) return { ok: false as const, reason: "scope_denied" as const };
  const where = { ...(query.entityType ? { entity_type: query.entityType } : {}), ...(query.scopeType ? { scope_type: query.scopeType } : {}), ...(query.programId ? { program_id: query.programId } : {}), ...(query.includeArchived ? {} : { archived_at: null }), ...(canAccess(actor, null) ? {} : { id: "00000000-0000-4000-8000-000000000000" }) };
  const fields = await prisma.custom_fields.findMany({ where, select, orderBy: [{ display_order: "asc" }, { created_at: "asc" }] });
  return { ok: true as const, data: fields.map((field) => serializeCustomField(field, actor)) };
}
export async function getCustomField(actor: AuthUser, id: string) { const field = await prisma.custom_fields.findUnique({ where: { id }, select }); if (!field || !canAccess(actor, field.program_id)) return { ok: false as const, reason: "not_found" as const }; return { ok: true as const, data: serializeCustomField(field, actor) }; }
export async function createCustomField(actor: AuthUser, input: CustomFieldInput, ipAddress?: string) {
  if (!assertScope(actor, input.programId).ok) return { ok: false as const, reason: "scope_denied" as const };
  if (!await activeGroup(input.groupId, input.entityType)) return { ok: false as const, reason: "group_not_found" as const };
  const programExists = input.programId ? await prisma.institution_programs.count({ where: { id: input.programId } }) : 1; if (!programExists) return { ok: false as const, reason: "program_not_found" as const };
  try { const result = await prisma.$transaction(async (tx) => { const field = await tx.custom_fields.create({ data: { module: input.entityType, field_key: input.fieldKey, field_label: input.fieldLabel, description: input.description, entity_type: input.entityType, group_id: input.groupId, scope_type: input.scopeType, program_id: input.programId, field_type: input.fieldType, is_required: input.isRequired, is_active: true, is_searchable: input.isSensitive || input.fieldType === "FILE" ? false : input.isSearchable, is_filterable: input.isSensitive || input.fieldType === "FILE" ? false : input.isFilterable, is_sensitive: input.isSensitive, display_order: input.displayOrder, options: json(input.options), validation_rules: json(input.validationRules), default_value: json(input.defaultValue), created_by_id: actor.id, updated_by_id: actor.id }, select }); await tx.audit_logs.create({ data: { user_id: actor.id, entity_type: "custom_field", entity_id: field.id, action: "create", ip_address: ipAddress, new_data: auditPayload(field) } }); return field; }); return { ok: true as const, data: serializeCustomField(result, actor) }; } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return { ok: false as const, reason: "duplicate_key" as const }; throw error; }
}
export async function updateCustomField(actor: AuthUser, id: string, input: Record<string, unknown>, ipAddress?: string) {
  const existing = await prisma.custom_fields.findUnique({ where: { id }, select: { ...select, _count: { select: { custom_field_values: true } } } }); if (!existing || !canAccess(actor, existing.program_id)) return { ok: false as const, reason: "not_found" as const };
  if (input.fieldType && input.fieldType !== existing.field_type && existing._count.custom_field_values > 0) return { ok: false as const, reason: "data_type_locked" as const };
  if ((input.programId !== undefined && input.programId !== existing.program_id) || (input.scopeType && input.scopeType !== existing.scope_type) || (input.entityType && input.entityType !== existing.entity_type)) return { ok: false as const, reason: "scope_locked" as const };
  if (typeof input.groupId === "string" && !await activeGroup(input.groupId, existing.entity_type ?? "")) return { ok: false as const, reason: "group_not_found" as const };
  const changes: any = { updated_by_id: actor.id, updated_at: new Date() }; for (const [camel, db] of Object.entries({ groupId: "group_id", fieldLabel: "field_label", description: "description", fieldType: "field_type", isRequired: "is_required", isSearchable: "is_searchable", isFilterable: "is_filterable", isSensitive: "is_sensitive", displayOrder: "display_order", options: "options", validationRules: "validation_rules", defaultValue: "default_value" })) if (camel in input) changes[db] = ["options", "validation_rules", "default_value"].includes(db) ? json(input[camel]) : input[camel]; if (changes.is_sensitive || changes.field_type === "FILE") { changes.is_searchable = false; changes.is_filterable = false; }
  const result = await prisma.$transaction(async (tx) => { const field = await tx.custom_fields.update({ where: { id }, data: changes, select }); await tx.audit_logs.create({ data: { user_id: actor.id, entity_type: "custom_field", entity_id: id, action: "update", ip_address: ipAddress, old_data: auditPayload(existing), new_data: auditPayload(field) } }); return field; }); return { ok: true as const, data: serializeCustomField(result, actor) };
}
export async function setCustomFieldStatus(actor: AuthUser, id: string, status: "activate" | "deactivate" | "archive", ipAddress?: string) { const existing = await prisma.custom_fields.findUnique({ where: { id }, select }); if (!existing || !canAccess(actor, existing.program_id)) return { ok: false as const, reason: "not_found" as const }; if (existing.archived_at) return { ok: false as const, reason: "already_archived" as const }; const data = status === "archive" ? { is_active: false, archived_at: new Date(), updated_by_id: actor.id, updated_at: new Date() } : { is_active: status === "activate", updated_by_id: actor.id, updated_at: new Date() }; const result = await prisma.$transaction(async (tx) => { const field = await tx.custom_fields.update({ where: { id }, data, select }); await tx.audit_logs.create({ data: { user_id: actor.id, entity_type: "custom_field", entity_id: id, action: status, ip_address: ipAddress, old_data: auditPayload(existing), new_data: auditPayload(field) } }); return field; }); return { ok: true as const, data: serializeCustomField(result, actor) }; }
export async function reorderCustomFields(actor: AuthUser, fieldIds: string[], ipAddress?: string) { const fields = await prisma.custom_fields.findMany({ where: { id: { in: fieldIds } }, select }); if (fields.length !== fieldIds.length || fields.some((field) => !canAccess(actor, field.program_id))) return { ok: false as const, reason: "not_found" as const }; const entity = fields[0]?.entity_type; const groupId = fields[0]?.group_id; const scope = fields[0]?.scope_type; const program = fields[0]?.program_id; if (fields.some((field) => field.entity_type !== entity || field.group_id !== groupId || field.scope_type !== scope || field.program_id !== program)) return { ok: false as const, reason: "different_group" as const }; await prisma.$transaction(async (tx) => { await Promise.all(fieldIds.map((id, index) => tx.custom_fields.update({ where: { id }, data: { display_order: index, updated_by_id: actor.id, updated_at: new Date() } }))); await tx.audit_logs.create({ data: { user_id: actor.id, entity_type: "custom_field", action: "reorder", ip_address: ipAddress, new_data: { entityType: entity, groupId, scopeType: scope, programId: program, fieldIds } } }); }); return { ok: true as const }; }
