import { Router } from "express";
import { z } from "zod";
import { requireAnyPermission, requireAuthentication } from "../../middlewares/auth.middleware";
import { createCustomFieldSchema, listCustomFieldSchema, reorderCustomFieldSchema, statusCustomFieldSchema, updateCustomFieldSchema } from "./custom-fields.schema";
import { createCustomField, getCustomField, listCustomFields, reorderCustomFields, setCustomFieldStatus, updateCustomField } from "./custom-fields.service";
import { customFieldEntityTypes } from "./custom-fields.types";
export const customFieldsRouter = Router(); customFieldsRouter.use(requireAuthentication);
const id = z.uuid(); const message: Record<string, string> = { scope_denied: "Bạn không có quyền truy cập chương trình tuyển sinh này.", not_found: "Không tìm thấy trường dữ liệu.", duplicate_key: "Mã trường đã tồn tại trong phạm vi áp dụng.", program_not_found: "Không tìm thấy chương trình tuyển sinh.", data_type_locked: "Không thể đổi kiểu dữ liệu khi trường đã có giá trị.", scope_locked: "Không thể đổi phạm vi của trường đã tạo.", already_archived: "Trường dữ liệu đã được lưu trữ.", different_group: "Chỉ có thể sắp xếp lại các trường cùng nhóm." };
function fail(response: any, result: any) { response.status(result.reason === "scope_denied" ? 403 : result.reason === "duplicate_key" ? 409 : result.reason === "not_found" ? 404 : 400).json({ message: message[result.reason] ?? "Không thể xử lý trường dữ liệu." }); }
customFieldsRouter.get("/", requireAnyPermission("custom_field.view"), async (req, res, next) => { try { const parsed = listCustomFieldSchema.safeParse(req.query); if (!parsed.success) return res.status(400).json({ message: "Tham số không hợp lệ." }); const result = await listCustomFields(req.authUser!, parsed.data); if (!result.ok) return fail(res, result); res.json(result.data); } catch (e) { next(e); } });
customFieldsRouter.patch("/reorder", requireAnyPermission("custom_field.update"), async (req, res, next) => { try { const parsed = reorderCustomFieldSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: "Dữ liệu sắp xếp không hợp lệ." }); const result = await reorderCustomFields(req.authUser!, parsed.data.fieldIds, req.ip); if (!result.ok) return fail(res, result); res.json({ message: "Đã cập nhật thứ tự trường dữ liệu." }); } catch (e) { next(e); } });
customFieldsRouter.get("/entity/:entityType", requireAnyPermission("custom_field.view"), async (req, res, next) => { try { const type = z.enum(customFieldEntityTypes).safeParse(req.params.entityType); if (!type.success) return res.status(400).json({ message: "Loại đối tượng không hợp lệ." }); const result = await listCustomFields(req.authUser!, { entityType: type.data, includeArchived: false }); if (!result.ok) return fail(res, result); res.json(result.data.filter((field) => field.isActive)); } catch (e) { next(e); } });
customFieldsRouter.post("/", requireAnyPermission("custom_field.create"), async (req, res, next) => { try { const parsed = createCustomFieldSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ message: "Dữ liệu trường không hợp lệ.", issues: parsed.error.issues }); if (parsed.data.isSensitive && !req.authUser!.permissions.includes("custom_field.edit_sensitive")) return res.status(403).json({ message: "Bạn không có quyền cấu hình trường nhạy cảm." }); const result = await createCustomField(req.authUser!, parsed.data, req.ip); if (!result.ok) return fail(res, result); res.status(201).json(result.data); } catch (e) { next(e); } });
customFieldsRouter.patch("/:id/status", requireAnyPermission("custom_field.archive"), async (req, res, next) => { try { const fieldId = id.safeParse(req.params.id), body = statusCustomFieldSchema.safeParse(req.body); if (!fieldId.success || !body.success) return res.status(400).json({ message: "Trạng thái trường không hợp lệ." }); const result = await setCustomFieldStatus(req.authUser!, fieldId.data, body.data.status, req.ip); if (!result.ok) return fail(res, result); res.json(result.data); } catch (e) { next(e); } });
customFieldsRouter.get("/:id", requireAnyPermission("custom_field.view"), async (req, res, next) => { try { const parsed = id.safeParse(req.params.id); if (!parsed.success) return res.status(400).json({ message: "Mã trường không hợp lệ." }); const result = await getCustomField(req.authUser!, parsed.data); if (!result.ok) return fail(res, result); res.json(result.data); } catch (e) { next(e); } });
customFieldsRouter.patch("/:id", requireAnyPermission("custom_field.update"), async (req, res, next) => { try { const fieldId = id.safeParse(req.params.id), body = updateCustomFieldSchema.safeParse(req.body); if (!fieldId.success || !body.success) return res.status(400).json({ message: "Dữ liệu cập nhật không hợp lệ.", issues: body.success ? undefined : body.error.issues }); if ((body.data.isSensitive === true || body.data.defaultValue !== undefined) && !req.authUser!.permissions.includes("custom_field.edit_sensitive")) return res.status(403).json({ message: "Bạn không có quyền cấu hình trường nhạy cảm." }); if (body.data.options !== undefined && !req.authUser!.permissions.includes("custom_field.manage_options")) return res.status(403).json({ message: "Bạn không có quyền quản lý lựa chọn trường dữ liệu." }); const result = await updateCustomField(req.authUser!, fieldId.data, body.data, req.ip); if (!result.ok) return fail(res, result); res.json(result.data); } catch (e) { next(e); } });
