import { emptyLeadForm } from "./lead.schema";
import type { LeadActionOptions, LeadDetail, LeadFormInput } from "./lead.types";

export function toLeadFormValues(lead: LeadDetail): LeadFormInput {
  return {
    ...emptyLeadForm,
    fullName: lead.fullName,
    phone: lead.phone ?? "",
    sourceId: lead.source?.id ?? "",
    pipelineStageId: lead.pipelineStage?.id ?? "",
    email: lead.email ?? "",
    gender: lead.gender ?? "",
    dateOfBirth: lead.dateOfBirth ?? "",
    cccd: lead.cccd ?? "",
    note: lead.note ?? "",
    status: lead.status ?? "new",
    temperature: lead.temperature ?? "",
    birthPlace: lead.birthPlace ?? "",
    cccdIssueDate: lead.cccdIssueDate ?? "",
    cccdIssuePlace: lead.cccdIssuePlace ?? "",
    nationality: lead.nationality ?? "",
    ethnicity: lead.ethnicity ?? "",
    religion: lead.religion ?? "",
    graduationYear: lead.graduationYear ?? "",
    graduationCertificate: lead.graduationCertificate ?? "",
    previousGraduationCertificate: lead.previousGraduationCertificate ?? "",
    graduationMajor: lead.graduationMajor ?? "",
    graduationRank: lead.graduationRank ?? "",
    diplomaIssuePlace: lead.diplomaIssuePlace ?? "",
    academicRank12: lead.academicRank12 ?? "",
    conductRank12: lead.conductRank12 ?? "",
    highSchoolName: lead.highSchoolName ?? "",
    highSchoolProvince: lead.highSchoolProvince ?? "",
    highSchoolDistrict: lead.highSchoolDistrict ?? "",
    currentJob: lead.currentJob ?? "",
    companyName: lead.companyName ?? "",
    specificAddress: lead.specificAddress ?? "",
    permanentAddress: lead.permanentAddress ?? "",
    currentAddress: lead.currentAddress ?? "",
    currentResidence: lead.currentResidence ?? "",
    province: lead.province ?? "",
    district: lead.district ?? "",
    ward: lead.ward ?? "",
    hamlet: lead.hamlet ?? "",
    relative1FullName: lead.relative1FullName ?? "",
    relative1Relationship: lead.relative1Relationship ?? "",
    relative1Phone: lead.relative1Phone ?? "",
    relative1Job: lead.relative1Job ?? "",
    relative1Address: lead.relative1Address ?? "",
    relative2FullName: lead.relative2FullName ?? "",
    relative2Relationship: lead.relative2Relationship ?? "",
    relative2Phone: lead.relative2Phone ?? "",
    relative2Job: lead.relative2Job ?? "",
    relative2Address: lead.relative2Address ?? "",
    institutionProgramId: lead.institutionProgramId ?? "",
    majorId: lead.majorId ?? "",
    admissionStatusId: lead.admissionStatusId ?? "",
    trainingCode: lead.trainingCode ?? "",
    classCode: lead.classCode ?? "",
    subjectGroupCode: lead.subjectGroupCode ?? "",
    subjectGroupName: lead.subjectGroupName ?? "",
    score1: lead.score1 ?? "",
    score2: lead.score2 ?? "",
    score3: lead.score3 ?? "",
    admissionScore: lead.admissionScore ?? "",
    enrollmentBatch: lead.enrollmentBatch ?? "",
    registrationStation: lead.registrationStation ?? "",
    decisionNumber: lead.decisionNumber ?? "",
    decisionSignedDate: lead.decisionSignedDate ?? "",
    monthlyRevenue: lead.monthlyRevenue ?? "",
    gclid: lead.gclid ?? "",
    tags: lead.tags,
  };
}

export function toLeadFormOptions(lead: LeadDetail, options?: LeadActionOptions) {
  return {
    sources: options?.sources ?? (lead.source ? [lead.source] : []),
    stages: options?.stages ?? (lead.pipelineStage ? [{ ...lead.pipelineStage, pipelineId: null, pipelineName: null }] : []),
    institutionPrograms: options?.institutionPrograms ?? [],
    majors: options?.majors ?? [],
    admissionStatuses: options?.admissionStatuses ?? [],
    tags: options?.tags ?? [],
  };
}
