import { Prisma } from "../../generated/prisma/client";
import { prisma } from "../../database/prisma";
import type { AuthUser } from "../auth/auth.types";
import { getLeadScopeWhere } from "./lead-list.service";

type Input = { fieldId: string; value: unknown };
type Field = Awaited<ReturnType<typeof prisma.custom_fields.findMany>>[number];
type Normalized = string | number | boolean | Date | string[] | null;

const leadValueWhere = (fieldId: string, leadId: string) => ({ custom_field_id_entity_type_entity_id: { custom_field_id: fieldId, entity_type: "LEAD", entity_id: leadId } });
const typedNulls = { value_text: null, value_number: null, value_date: null, value_boolean: null, value_json: Prisma.JsonNull };
function readValue(field: Field, row: any): Normalized { if (!row) return null; if (["TEXT","TEXTAREA","EMAIL","PHONE","SELECT"].includes(field.field_type)) return row.value_text; if (field.field_type === "NUMBER") return row.value_number === null ? null : Number(row.value_number); if (["DATE","DATETIME"].includes(field.field_type)) return row.value_date; if (field.field_type === "BOOLEAN") return row.value_boolean; return Array.isArray(row.value_json) ? row.value_json.filter((v: unknown): v is string => typeof v === "string") : null; }
function auditValue(field: Field, value: Normalized): Prisma.InputJsonValue { if (field.is_sensitive) return { redacted: true, hasValue: value !== null }; if (value === null) return { cleared: true }; if (value instanceof Date) return value.toISOString(); if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") return value; return value; }
function normalize(field: Field, raw: unknown): Normalized | null { if (raw === null || (typeof raw === "string" && raw.trim() === "")) return field.is_required ? null : null; const rules = (field.validation_rules ?? {}) as Record<string, unknown>; const options = new Set(((field.options ?? []) as Array<{ code?: unknown; isActive?: unknown }>).filter((x) => x.isActive).map((x) => x.code).filter((x): x is string => typeof x === "string")); if (["TEXT","TEXTAREA"].includes(field.field_type) && typeof raw === "string") { const v=raw.trim(); if ((typeof rules.maxLength === "number" && v.length > rules.maxLength) || (typeof rules.minLength === "number" && v.length < rules.minLength)) return null; return v; } if (field.field_type === "NUMBER" && typeof raw === "number" && Number.isFinite(raw)) return raw; if (field.field_type === "BOOLEAN" && typeof raw === "boolean") return raw; if (field.field_type === "DATE" && typeof raw === "string" && /^\d{4}-\d{2}-\d{2}$/.test(raw)) return new Date(`${raw}T00:00:00.000Z`); if (field.field_type === "DATETIME" && typeof raw === "string" && !Number.isNaN(Date.parse(raw))) return new Date(raw); if (field.field_type === "EMAIL" && typeof raw === "string" && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(raw)) return raw.trim().toLowerCase(); if (field.field_type === "PHONE" && typeof raw === "string" && /^\d{10}$/.test(raw.trim())) return raw.trim(); if (field.field_type === "SELECT" && typeof raw === "string" && options.has(raw)) return raw; if (field.field_type === "MULTI_SELECT" && Array.isArray(raw) && raw.every((v) => typeof v === "string" && options.has(v)) && new Set(raw).size === raw.length) return raw; return null; }
function applicable(programId: string | null) { return { entity_type:"LEAD", is_active:true, archived_at:null, OR:[{scope_type:"GLOBAL"}, ...(programId ? [{scope_type:"PROGRAM",program_id:programId}] : [])] }; }
async function leadFor(user: AuthUser, leadId: string) { return prisma.leads.findFirst({ where:{id:leadId,deleted_at:null,...getLeadScopeWhere(user)}, select:{id:true,institution_program_id:true} }); }
export async function getLeadCustomFields(user: AuthUser, leadId: string) { const lead=await leadFor(user,leadId); if (!lead) return null; const fields=await prisma.custom_fields.findMany({where:applicable(lead.institution_program_id),include:{custom_field_values:{where:{entity_type:"LEAD",entity_id:lead.id}}},orderBy:[{display_order:"asc"},{id:"asc"}]}); const viewSensitive=user.permissions.includes("custom_field.view_sensitive"), canEdit=user.permissions.some((p)=>["lead.update_all","lead.update_department","lead.update_assigned"].includes(p)); return {fields:fields.map((f)=>({id:f.id,code:f.field_key,name:f.field_label,description:f.description,dataType:f.field_type,isRequired:f.is_required??false,isSensitive:f.is_sensitive??false,displayOrder:f.display_order??0,options:f.options,validationRules:f.validation_rules,defaultValue:f.is_sensitive&&!viewSensitive?undefined:f.default_value,value:f.is_sensitive&&!viewSensitive?null:readValue(f,f.custom_field_values[0]),canView:!f.is_sensitive||viewSensitive,canEdit:canEdit&&(!f.is_sensitive||user.permissions.includes("custom_field.edit_sensitive"))}))}; }
export async function getLeadCustomFieldDefinitions(user: AuthUser, programId: string | null, canEdit: boolean) { const fields=await prisma.custom_fields.findMany({where:applicable(programId),orderBy:[{display_order:"asc"},{id:"asc"}]}); const viewSensitive=user.permissions.includes("custom_field.view_sensitive"); return {fields:fields.map((f)=>({id:f.id,code:f.field_key,name:f.field_label,description:f.description,dataType:f.field_type,isRequired:f.is_required??false,isSensitive:f.is_sensitive??false,displayOrder:f.display_order??0,options:f.options,validationRules:f.validation_rules,defaultValue:f.is_sensitive&&!viewSensitive?undefined:f.default_value,value:f.is_sensitive&&!viewSensitive?null:readValue(f,null),canView:!f.is_sensitive||viewSensitive,canEdit:canEdit&&(!f.is_sensitive||user.permissions.includes("custom_field.edit_sensitive"))}))}; }
export async function patchLeadCustomFields(user: AuthUser, leadId: string, values: Input[], ip?: string) { const lead=await leadFor(user,leadId); if (!lead) return {ok:false as const,reason:"not_found"}; if (!user.permissions.some((p)=>["lead.update_all","lead.update_department","lead.update_assigned"].includes(p))) return {ok:false as const,reason:"forbidden"}; const fields=await prisma.custom_fields.findMany({where:{...applicable(lead.institution_program_id),id:{in:values.map(v=>v.fieldId)}}}); if(fields.length!==values.length) return {ok:false as const,reason:"not_applicable"}; const map=new Map(fields.map(f=>[f.id,f])); const prepared=values.map(v=>({field:map.get(v.fieldId)!,value:normalize(map.get(v.fieldId)!,v.value)})); if(prepared.some(x=>x.field.is_sensitive&&!user.permissions.includes("custom_field.edit_sensitive"))) return {ok:false as const,reason:"sensitive_forbidden"}; if(prepared.some(x=>x.value===null&&x.field.is_required)||prepared.some((x,i)=>x.value===null&&values[i].value!==null&&values[i].value!=="")) return {ok:false as const,reason:"invalid"}; await prisma.$transaction(async tx=>{for(const item of prepared){const old=await tx.custom_field_values.findUnique({where:leadValueWhere(item.field.id,lead.id)});const oldValue=readValue(item.field,old);if(item.value===null){if(old)await tx.custom_field_values.delete({where:{id:old.id}});}else{const data:any={...typedNulls,custom_field_id:item.field.id,entity_type:"LEAD",entity_id:lead.id,updated_at:new Date(),value:null};if(["TEXT","TEXTAREA","EMAIL","PHONE","SELECT"].includes(item.field.field_type)){data.value_text=item.value;data.value=item.value;}else if(item.field.field_type==="NUMBER")data.value_number=item.value;else if(["DATE","DATETIME"].includes(item.field.field_type))data.value_date=item.value;else if(item.field.field_type==="BOOLEAN")data.value_boolean=item.value;else data.value_json=item.value;await tx.custom_field_values.upsert({where:leadValueWhere(item.field.id,lead.id),create:data,update:data});}await tx.audit_logs.create({data:{user_id:user.id,entity_type:"lead_custom_field",entity_id:lead.id,action:item.value===null?"clear":"update",ip_address:ip,old_data:{fieldId:item.field.id,fieldCode:item.field.field_key,dataType:item.field.field_type,value:auditValue(item.field,oldValue)},new_data:{fieldId:item.field.id,fieldCode:item.field.field_key,dataType:item.field.field_type,value:auditValue(item.field,item.value)}}});}});return {ok:true as const}; }
