export const vietnamProvinces = [
  { code: "tuyen_quang", label: "Tuyên Quang" },
  { code: "lao_cai", label: "Lào Cai" },
  { code: "thai_nguyen", label: "Thái Nguyên" },
  { code: "phu_tho", label: "Phú Thọ" },
  { code: "bac_ninh", label: "Bắc Ninh" },
  { code: "hung_yen", label: "Hưng Yên" },
  { code: "hai_phong", label: "Hải Phòng" },
  { code: "ninh_binh", label: "Ninh Bình" },
  { code: "quang_tri", label: "Quảng Trị" },
  { code: "da_nang", label: "Đà Nẵng" },
  { code: "quang_ngai", label: "Quảng Ngãi" },
  { code: "gia_lai", label: "Gia Lai" },
  { code: "khanh_hoa", label: "Khánh Hòa" },
  { code: "lam_dong", label: "Lâm Đồng" },
  { code: "dak_lak", label: "Đắk Lắk" },
  { code: "tp_ho_chi_minh", label: "Thành phố Hồ Chí Minh" },
  { code: "dong_nai", label: "Đồng Nai" },
  { code: "tay_ninh", label: "Tây Ninh" },
  { code: "can_tho", label: "Cần Thơ" },
  { code: "vinh_long", label: "Vĩnh Long" },
  { code: "dong_thap", label: "Đồng Tháp" },
  { code: "ca_mau", label: "Cà Mau" },
  { code: "an_giang", label: "An Giang" },
  { code: "ha_noi", label: "Hà Nội" },
  { code: "hue", label: "Huế" },
  { code: "lai_chau", label: "Lai Châu" },
  { code: "dien_bien", label: "Điện Biên" },
  { code: "son_la", label: "Sơn La" },
  { code: "lang_son", label: "Lạng Sơn" },
  { code: "quang_ninh", label: "Quảng Ninh" },
  { code: "thanh_hoa", label: "Thanh Hóa" },
  { code: "nghe_an", label: "Nghệ An" },
  { code: "ha_tinh", label: "Hà Tĩnh" },
  { code: "cao_bang", label: "Cao Bằng" },
] as const;

export const vietnamProvinceByCode = new Map(vietnamProvinces.map((province) => [province.code, province.label]));
